theme: jekyll-theme-primer
title: Mon Site Statique
description: Site hébergé sur GitHub Pages
url: "https://elleuchbrahimkhalil.github.io"
baseurl: "/htdocs"
exclude:
  - .history
  - _site
  - vendor
  - node_modules
